# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

public_key = File.read("id_rsa.pub")

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "centos#{i}" do |centos|
      centos.vm.box = BOX_IMAGE
      centos.vm.hostname = "centos#{i}"
      centos.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      centos.vm.provision :"shell", inline: "
       mkdir -p /home/vagrant/.ssh
       echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
       echo 'Host *' >> /home/vagrant/.ssh/config
       echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
       echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
       chmod -R 600 /home/vagrant/.ssh/config
       chmod -R 644 /home/vagrant/.ssh/authorized_keys
       chown vagrant:vagrant .ssh/config
       chmod 700 /home/vagrant/.ssh"
      centos.vm.provision :"shell", path: "disableselinux.sh"
    end
   end
    config.vm.define "ubuntu" do |ubuntu|
     ubuntu.vm.box = "ubuntu/trusty64"
     ubuntu.vm.hostname = "ubuntu"
     ubuntu.vm.network :private_network, ip: "10.0.0.9"
     ubuntu.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
   end
   config.vm.define "master" do |master|
    master.vm.box = BOX_IMAGE
    master.vm.hostname = "master"
    master.vm.network :private_network, ip: "10.0.0.10"
    master.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    master.vm.provision :"shell", path: "bootstrap-ansible.sh"
    master.vm.provision :"shell", path: "disableselinux.sh"
   end
end