# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

public_key = File.read("id_rsa.pub")

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      subconfig.vm.provision :"shell", inline: "
       mkdir -p /home/vagrant/.ssh
       chmod 700 /home/vagrant/.ssh
       echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
       chmod -R 600 /home/vagrant/.ssh/authorized_keys
       echo 'Host 10.0.*.*' >> /home/vagrant/.ssh/config
       echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
       echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
       chmod -R 600 /home/vagrant/.ssh/config 
       "
    end  
  end
   config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
    subconfig.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    subconfig.vm.provision :"shell", path: "bootstrap-ansible.sh"
  end
end
